### ISSUE TITLE
When I try to run

### ISSUE THREAD

**Issue by truta193** [BobbyWibowo/Lightbringer#1]
[Fixed, thanks]

So I've downloaded it, installed and when I tried to run this popped up for a few seconds before automatically closing.

[![Screenshot from Gyazo](https://gyazo.com/eb4161cf13f7d3894625b659ff265853/raw)](https://gyazo.com/eb4161cf13f7d3894625b659ff265853)

Any help?

**Comment by BobbyWibowo** [comment]
Hello,

You must be running Node.js which enables async/await feature by default
(such as >=7.6 and 8.x). If installing 8.x is not an option, you can try to Google
the version of your Node.js and find some information about how to enable
it (some <=7.6 versions can enable it through a "flag"). If you're running
6.x though, better to just upgrade to 8.x.

Sent with Gmail for Android (Xiaomi Mi 5s)

**Comment by BobbyWibowo** [comment]
I added an experimental check in 928ad32167dbb6a25dff4d6249c2487fbe5ca541 which will, hopefully, automatically enable the "flag" for node `>= 7.0.x` & `< 7.6.x`. Though you will still need to update to either `7.x` or `8.x` if you're still on `6.x`. I've also updated the `package.json` file with the required node version so that hopefully people will get a more obvious error message when they run `yarn start` with an unsupported node version.
